services:
  legacy-prns:
    build:
      dockerfile: Dockerfile
    ports:
      - '8085:8085'
    environment:
      ASPNETCORE_URLS: http://+:8085
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8085/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
